force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Driver List</relationshipLabel>
    <relationshipName>ContactJobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer List</relationshipLabel>
    <relationshipName>AccountJobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyInvitation/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Survey Invitations</relationshipLabel>
    <relationshipName>Survey_Invitations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyInvitation/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Survey Invitations</relationshipLabel>
    <relationshipName>Survey_Invitations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyInvitation/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Survey Invitations</relationshipLabel>
    <relationshipName>Survey_Invitations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SentSurveyInvitaionLink.cls
public class SentSurveyInvitaionLink {
    
    @InvocableMethod
    public static void SentLink(List<String> InvitationId)
    {
        String SyrveyInvitationId= InvitationId[0];
        system.debug('===SyrveyInvitationId==='+SyrveyInvitationId);
        List<SurveyInvitation> lstSurInvitation=[Select Id , 
                                                 name,
                                                 ParticipantId,
                                                 InvitationLink,
                                                 Contact__c, 
                                                 Contact__r.Personal_Email__c, 
                                                 Contact__r.Email, 
                                                 Contact__r.Name, 
                                                 Contact__r.Phone, 
                                                 Contact__r.HomePhone, 
                                                 Contact__r.OwnerId, 
                                                 Contact__r.MobilePhone, 
                                                 Customer__c,
                                                 Customer__r.Name,
                                                 Customer__r.Email__c,
                                                 Job__c, 
                                                 Job__r.Name, 
                                                 Survey.DeveloperName,
                                                 CommunityId,
                                                 community.Name,
                                                 UUID
                                                 from SurveyInvitation 
                                                 where Id =:SyrveyInvitationId];
        system.debug('===lstSurInvitation==='+lstSurInvitation[0]);
        List<EmailTemplate> eTemplate=[Select Id,DeveloperName, Name, Subject, HtmlValue 
                                       from Emailtemplate where DeveloperName = 'Survey_Template' Limit 1 ];
        system.debug('===eTemplate==='+eTemplate[0]);
        List<Messaging.SingleEmailMessage> emailnotifications=new List<Messaging.SingleEmailMessage>();
        system.debug('===eTemplate==='+eTemplate.size() +' '+lstSurInvitation.size()+' '+lstSurInvitation[0].Customer__r.Email__c);
        if(eTemplate.size()>0 && lstSurInvitation.size()>0
           && eTemplate[0].HtmlValue != null  
           && lstSurInvitation[0].Customer__r.Email__c != null)
        {
            Messaging.SingleEmailMessage email=new Messaging.SingleEmailMessage();
            List<String> toEmailAddress=new List<String>();
            List<String> toEmailBCCAddress=new List<String>();
            toEmailAddress.add(lstSurInvitation[0].Customer__r.Email__C);            
            email.setToAddresses(toEmailAddress);           
            email.setSubject(eTemplate[0].Subject);
            email.setHtmlBody(eTemplate[0].HtmlValue);
            email.setHtmlBody(email.getHtmlBody().replace('CONTACT_NAME',lstSurInvitation[0].Customer__r.Name));
            email.setHtmlBody(email.getHtmlBody().replace('SURVEY_LINK',lstSurInvitation[0].InvitationLink));
            emailnotifications.add(email);
            system.debug('===emailnotifications==='+emailnotifications);
            Messaging.sendEmail(emailnotifications);
        }
    }
    
}